sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
after_success:
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf LDM-230.pdf --upload --lsstdoc LDM-230.tex --env=travis --ltd-product $PRODUCT"
env:
  global:
    - PRODUCT="ldm-230"
    # LSST the Docs credentials
    - secure: "la8ntRBcvXZsRipxLJYg95sGH+EZKG0lRJ7pdfrRyqINqbQUhBgh563yRV2oWxrqyjzn9XCtW/mR8iX3ZonLKxO2so4M9EgIO8tcRBuGuPAhvJQOiD3l2sggRQYmXygq/dieZHjGaYmolggWC0NxLbaiolY2/bNmQrGjxESVztPXZLX+bpSzHrwWvYPgMxAukzzQ3eWDrpcrXuHYnU4TLIYK8rKEHRwRTdRC62xPCvH28L5Z8gwAS4lEQebfuPEP/pGQakOzQjPmSv6ko1UQBbOuID2UBrEhbzQ/7dIJR6oORaNK2QPmwvy26j32XIxYDIm/d/ulZRlERFZF99WBw61QeNXNDXitALEcr7dLuLzVOP9uR22FyRsl5921CChNdM0pS6L7AHz1AHo4sHFlCDTDDeyeHtlfo287zydqfnftruwKqIgQphXOTxHVQ29v2YSFW/pn7b18XIgGCx3NRr5TMBKeOpn2LA+pNUJITLg4AhMu/OkW5HzStNbOcn/jtxiqP5D8iWJlUx3UjLRRZE084AbNALNEwwATk0G/4t1HJl58ZV5SmwkqJpGevIxtZ7GY/VnRGyPTziIjWFEqBMRwtNk3S6G7kkQ8FydJYUfOGHXHWbAqbgX7PQASXOtt4K/BNA393/oydnclv5hpG2ZmSz7EOD5PRNzAq7rqnVg="
    - secure: "Dbv5TD/gKm+wOIyjCdrAQYtNyj36qjOcsFrrjh2oM09Q2TBhbTKyhjKjcp304B7piwIrnpZoCV8sQquZkjE9wHBcuWhWVqZQ83xl5GcLjDavZ+Xwk4E+pZ7OjBzagBM5fHTHU+bNTbr1WL8unt9a1IjVcLYxZdEmnS0mCjU+2oytZF/MbOiP21aLRHGa2Y/JOGU3xL1aQDkuTYC0a75xg/WM/4ukvrzEtSE4eEhvcd7WWjjWQogcTAeN1t04RAIlfJ//i5s6KAFISynpPVjH+cEoJG7x39XKOYIViavbQMpaRgN8i+Bjtd1wfnwqGPuR3V2qJ0/z/KlPzIKP/AY6kXhAwA16n8MPR8imr0RSMqH5yGuaD17gzmv480Wz4Rqoa640jzsx82np35bKZegmUZCjVgT0RW9kzVjM7H4QUn3U8DpSA9jfy6Guc54F8sOEGMxCYLpkiIZPfFSOF78QGF/SX8iSLn/mFur87IgIgDjT03IzUgJeDkRAE26XaEPcIle5ZO2Si4aG6mQrEr4ANWdP3IYNs+/MnbpYPv16hJ4T7H3pZd7XuHzJBLZm1N9UV1FNluDVtm9C9be8G8mervFYzB/BRqX2fOgP05NZKlEUAeb+RkHs6BCVbl3Itl/gmaqYJLA8cuHxwN3364z5OqIbKkVTsonTbwuPANIQ8eo="
